### ISSUE TITLE
Prometheus metrics doesn't report events even when 'enable-prometheus' is true

### ISSUE THREAD

**Issue by yejingchen** [heptiolabs/eventrouter#89] opened 2019-10-12 02:53 UTC
After commit 6a815be, the http `/metrics` interface gives no kubernetes events either with `enable-prometheus` set to `true` or not specified at all. Events are indeed recorded because it is logged in glog.

After fast skimming I think the `viper` imported in `eventrouter.go` is not the same instance in `main.go` so the config doesn't apply. But since I don't know about go I maybe wrong.
https://github.com/heptiolabs/eventrouter/blob/6a815beeeab89b29e5c283f7c793964b0b67e05a/eventrouter.go#L25

**Comment by cyrus-mc** [comment] 2019-11-07 21:45
@yejingchen I pushed a quick fix for this.

The issue is that the init function is called before loadConfig (which sets enable-prometheus). Therefore the config value is not found and the if statement evaluated false. I moved what was in the init function to the NewEventRouter function.

**Closed** 2019-12-05 21:30 UTC
